image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/gitlab.com/coderlane /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/coderlane/go-ipfs-stat-top
  - ln -s /go/src/gitlab.com/coderlane /go/src/_/builds/coderlane
  - make dep

unit_tests:
  stage: test
  script:
    - make test

code_coverage:
  stage: test
  script:
    - make coverage

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make
